<?php

namespace CE\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends EntityRepository
{
}
