<?php

namespace CE\ConfigBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntriesRepository extends EntityRepository
{
    
}
