imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ CEAnnounceBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    FOSUserBundle: ~
                    SonataUserBundle: ~
                    ApplicationSonataUserBundle: ~
                    SonataMediaBundle: ~
                    ApplicationSonataMediaBundle: ~
                    SonataAdminBundle: ~
                    ApplicationSonataAdminBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: ssl
    auth_mode:  login

#FOSUserBundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CE\UserBundle\Entity\User
    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            #handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            #validation_groups:  [Authentication] # Please note : this is not the default value
    registration:
        form:
            handler: test_user.form.handler.registration
    resetting:
        email:
            from_email:
                address:        no-reply@ceicl-lille.fr
                sender_name:    Comité Etablissement - ICL Lille
    service:
        mailer: fos_user.mailer.twig_swift
        
sonata_admin:
    title:      Administration
    templates:
        ## default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        ## default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
        history: SonataAdminBundle:CRUD:history.html.twig
        preview: SonataAdminBundle:CRUD:preview.html.twig
        delete:  SonataAdminBundle:CRUD:delete.html.twig
    dashboard:
        blocks:
            # display two dashboard blocks
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [users_page, news_page, activity_page, announce_page, media_page, message_page, misc_page]
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <div class="panel-group" id="accordion">
                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                                  Comment activer/désactiver un utilisateur?
                                </a>
                              </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in">
                              <div class="panel-body">
                                <ul>
                                  <li>Une fois que l'utilisateur s'est enregistré, il faut lui activer son compte:</li>
                                  <li>Cliquer sur le menu Liste de la partie <b>Utilisateurs</b>.</li>
                                  <li>Dans la colonne <b>Activé</b> vous pouvez voir si l'utilisateur est activé ou non.</li>
                                  <li>Pour l'activer (ou le désactiver) il suffit de cliquer sur non ou (oui) pour le changer d'état.</li>
                                </ul>
                              </div>
                            </div>
                          </div>
                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                                  Comment modifier un utilisateur?
                                </a>
                              </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse">
                              <div class="panel-body">
                                <ul>
                                  <li>Pour modifier un utilisateur: </li>
                                  <li>Cliquer sur le menu <b>Liste</b> de la partie <b>Utilisateurs</b>.</li>
                                  <li>Cliquer sur l'utilisateur que vous souhaitez modifier.</li>
                                  <li>Faites vos modifications.</li>
                                  <li>Pour <b>enregister</b> ces modifications cliquer sur le bouton <b>Mettre à jour</b> de votre choix.</li>
                                </ul>
                              </div>
                            </div>
                          </div>
                          <div class="panel panel-default">
                            <div class="panel-heading">
                              <h4 class="panel-title">
                                <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                                  Collapsible Group Item #3
                                </a>
                              </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse">
                              <div class="panel-body">
                                Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
                              </div>
                            </div>
                          </div>
                        </div>
        groups:
            users_page:
                label: Utilisateurs
                items:
                    - sonata.user.admin.user
                    - ce.contact.admin.staff
            news_page:
                label: Actualités
                items:
                    - ce.news.admin.post
                    - ce.news.admin.comment
            activity_page:
                label: Activités
                items:
                    - ce.activity.admin.activity
                    - ce.activity.admin.category
            announce_page:
                label: Annonces
                items:
                    - ce.announce.admin.post
            media_page:
                label: Médiathèque
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            misc_page:
                label: Divers
                items:
                    - ce.config.admin.entries
                    - ce.report.admin.report
            message_page:
                label: Messages
                items:
                    - ce.contact.admin.message
                    - ce.contact.admin.category
                    
                    
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.admin.block.search_result:
            
sonata_user:
    security_acl:     false
    class:
        user:         CE\UserBundle\Entity\User
    admin:                  # Admin Classes
        user:
            class:          CE\UserBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
 
        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile_custom    
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]
            
sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
 
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
        icone_news:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 900, height: 300, quality: 70}
        staff:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 200, height: 300, quality: 70}
        activity_file:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.file
            formats: []
        report_file:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.file
            formats: []
        news_file:
            download:
                strategy: sonata.media.security.connected_strategy
                mode: http
            providers:
                - sonata.media.provider.file
            formats: []
    cdn:
        server:
            path: /site-ce/web/uploads/media
 
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: ".tinymce"
    # Get current language from the parameters.ini
    language: %locale%
    # Custom buttons
    tinymce_buttons:
        stfalcon: # Id of the first button
            title: "Stfalcon"
            image: "http://stfalcon.com/favicon.ico"
    theme:
        # Simple theme: same as default theme
        simple: ~
        # Advanced theme with almost all enabled plugins
        advanced:
             plugins:
                 - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                 - "searchreplace wordcount visualblocks visualchars code fullscreen"
                 - "insertdatetime media nonbreaking save table contextmenu directionality"
                 - "emoticons template paste textcolor"
             toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
             toolbar2: "print preview media | forecolor backcolor emoticons "
             image_advtab: true
             templates:
                 - {title: 'Test template 1', content: 'Test 1'}
                 - {title: 'Test template 2', content: 'Test 2'}
        # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
        bbcode:
             plugins: ["bbcode, code, link, preview"]
             menubar: false
             toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
                
mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~
    
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }