ce_twig_extension:
    resource: "@CETwigExtensionBundle/Resources/config/routing.yml"
    prefix:   /

ce_home:
    resource: "@CEHomeBundle/Resources/config/routing.yml"
    prefix:   /

ce_contact:
    resource: "@CEContactBundle/Resources/config/routing.yml"
    prefix:   /contact

ce_config:
    resource: "@CEConfigBundle/Resources/config/routing.yml"
    prefix:   /config

ce_activity:
    resource: "@CEActivityBundle/Resources/config/routing.yml"
    prefix:   /activite

ce_media:
    resource: "@CEMediaBundle/Resources/config/routing.xml"
    prefix:   /media

ce_report:
    resource: "@CEReportBundle/Resources/config/routing.yml"
    prefix:   /rapport

ce_announce:
    resource: "@CEAnnounceBundle/Resources/config/routing.yml"
    prefix:   /annonce

ce_news:
    resource: "@CENewsBundle/Resources/config/routing.yml"
    prefix:   /actualite

ce_user:
    resource: "@CEUserBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
 
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /utilisateur/profil
 
fos_user_register:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/registration.xml"
    prefix: /enregistrement
 
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /renouvellement
 
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /utilisateur/profil

fos_user_profile_show:
    pattern:  /utilisateur/profil
    defaults: { _controller: SonataUserBundle:Profile:show }
    requirements:
        _method: GET
        
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
 
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media