<?php

namespace CE\ActivityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends EntityRepository
{
    public function getActiveActivities() {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.category', 'c')
                ->addSelect('c')
                ->where('a.active = 1 and c.active = 1')
                ->orderBy('a.date', 'desc');

        return $qb->getQuery()
                        ->getResult();
    }
}
