<?php

namespace CE\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {

    public function getPostWithComments($id) {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.comments', 'c')
                ->addSelect('c')
                ->where('a.id = :id and a.active = 1')
                ->setParameter('id', $id);

        return $qb->getQuery()
                        ->getSingleResult();
    }

    public function getLatestsPostsWithComments($numberOfLatestsPosts) {
        $qb = $this->createQueryBuilder('a')
                ->leftJoin('a.comments', 'c')
                ->addSelect('c')
                ->setMaxResults($numberOfLatestsPosts)
                ->where('a.active = 1')
                ->orderBy('a.date', 'desc');

        return $qb->getQuery()
                        ->getResult();
    }

    public function getPostsBySearchCriteria($searchEntry) {
        $qb = $this->createQueryBuilder('a') 
                ->where('(a.title LIKE :searchEntry OR a.content LIKE :searchEntry) AND a.active = 1')
                ->setParameter('searchEntry', '%'.$searchEntry.'%')
                ->orderBy('a.date', 'desc');

        return $qb->getQuery()
                        ->getResult();
    }

}

